Implement event-driven validation for ODT message ingestion
Planning-Inspectorate/ODW-Service pull request #936
Opened 2023-12-14 16:06 UTC by chrisdalykinandcarta

**PR Template**

 1. Are there new source to raw datasets?
	
	 - [ ] If yes - has a trigger been attached at the appropriate frequency?
  	 - [ ] No

 2. Have any new tables been created in Standardised?

  	- [ ] No
   	- [ ] If yes:
		- [ ] orchestration.json has been updated and tested in Dev and has been / is about to be PRd into main
		- [ ] the new schema exists inside *odw-config/standardised-table-definitions* OR is about to be PRd into main
			- Make sure to run Platform Integrate and Platform Deploy to Dev at least to ensure the schema is deployed into Synapse Dev Live 
		- [ ] Is the raw-to-standardised python script scheduled to run for this dataset grouping?
 3. Have any new tables been created in Harmonised or Curated?

   	 - [ ] No
     	 - [ ] If yes
	 	- [ ]  *2-odw-standardised-to-harmonised/py_odw_harmonised_table_creation* OR 4-*odw-harmonised-to-curated/py_odw_curated_table_creation* are set up to run in the pipeline *pln_post_deployments* with the base parameter specifying the correct table
		- [ ] the new schema exists inside *odw-config/harmonised-table-definitions* / *odw-config/curated-table-definitions* OR is about to be PRd into main
			- Make sure to run Platform Integrate and Platform Deploy to Dev at least to ensure the schema is deployed into Synapse Dev Live 
 4. Have any tables changed AND/OR have any columns changed in any scripts?
We only care about new columns or columns that change type.
	- [ ] No
 	- [ ] If yes:
		- [ ] Please set py_change_table to run in the pipeline *pln_post_deployments*
		- [ ] Please create a script to backdate and fill in this new column in Test and Prod
			Only delete and recreate tables with caution!
 4. Have any scripts run in isolation in dev? Please look at the *"spark.autotune.trackingId"*
		- If these changes need to be reflected in Test and Prod, please add to the pipeline *post-			deployment/pln_post_deployment*
	- [ ] Yes - I have reflected this script in the *pln_post_deployments* pipeline
	- [ ] Yes - This script is part of a scheduled run and has been added to the appropriate end to end pipeline with a trigger at the correct frequency
	- [ ] No - This change does not need to take place in Test and Prod
	- [ ] No - No scripts have run

2023-12-14 17:06 UTC, ChrisToppingKandC requested changes
Initial look at this and it looks good in terms of logic. I would suggest a couple of minor improvements. Any generic functions being called should be held in a separate file, e.g. process_message. Likewise, config like the schema mappings can be held elsewhere and imported instead. 

Commented out lines with # I don't think are accepted when deployed to Azure but I'll check that next week. 

I would also add type hints to all functions to indicate what it accepts and what it returns, e.g.  str, dict or whatever. It's there for some but not for others. If it's hard to know the type of object it will take or return then it's fine to leave it but I can take a look at that next week.

I'll pull this branch and test myself properly on Monday.

Because the above is all just cosmetic and good python guidance it won't make or break the code so don't bother changing anything just yet.

Good work though, cheers.

2023-12-15 10:03 UTC, chrisdalykinandcarta commented
> Initial look at this and it looks good in terms of logic. I would suggest a couple of minor improvements. Any generic functions being called should be held in a separate file, e.g. process_message. Likewise, config like the schema mappings can be held elsewhere and imported instead.
> 
> Commented out lines with # I don't think are accepted when deployed to Azure but I'll check that next week.
> 
> I would also add type hints to all functions to indicate what it accepts and what it returns, e.g. str, dict or whatever. It's there for some but not for others. If it's hard to know the type of object it will take or return then it's fine to leave it but I can take a look at that next week.
> 
> I'll pull this branch and test myself properly on Monday.
> 
> Because the above is all just cosmetic and good python guidance it won't make or break the code so don't bother changing anything just yet.
> 
> Good work though, cheers.

Cheers mate - all really good suggestions, thanks for the feedback! I'm going to leave this PR here as a POC as I have to pivot to other work today, but would be great if you could make those changes next week (or whenever you're free). 

Regarding the dynamic pulling in of schemas, I think Ben has an idea around that - we might be able to just distribute a Python package with the schema repo.

2023-12-15 10:06 UTC, chrisdalykinandcarta commented
One more thing - you'll have to assign subscription permissions to your existing function app in terraform, but I wonder if these have already been assigned - so you might be able to just use this code directly by deploying it to the existing function app and re-factoring it.

2024-06-25 12:32 UTC, closed without merging

2024-06-25 12:32 UTC, ChrisToppingKandC commented
No required at the moment.